/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AssetId = IDL.Nat;
export const Outcome = IDL.Variant({ 'fail' : IDL.Null, 'pass' : IDL.Null });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Status = IDL.Variant({
  'active' : IDL.Null,
  'inStorage' : IDL.Null,
  'underMaintenance' : IDL.Null,
  'retired' : IDL.Null,
});
export const Time = IDL.Int;
export const Category = IDL.Variant({
  'vehicles' : IDL.Null,
  'other' : IDL.Null,
  'furniture' : IDL.Null,
  'itEquipment' : IDL.Null,
  'machinery' : IDL.Null,
  'officeSupplies' : IDL.Null,
});
export const Specification = IDL.Record({
  'status' : Status,
  'assignedTo' : IDL.Opt(IDL.Text),
  'purchaseDate' : Time,
  'supplier' : IDL.Text,
  'cost' : IDL.Float64,
  'name' : IDL.Text,
  'serialNumber' : IDL.Text,
  'notes' : IDL.Text,
  'category' : Category,
  'location' : IDL.Text,
});
export const Data = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'assignedTo' : IDL.Opt(IDL.Text),
  'purchaseDate' : Time,
  'supplier' : IDL.Text,
  'cost' : IDL.Float64,
  'name' : IDL.Text,
  'serialNumber' : IDL.Text,
  'notes' : IDL.Text,
  'category' : Category,
  'location' : IDL.Text,
});
export const Data__4 = IDL.Record({
  'assigned' : IDL.Nat,
  'total' : IDL.Nat,
  'underMaintenance' : IDL.Nat,
  'recentlyAdded' : IDL.Nat,
});
export const Data__3 = IDL.Record({
  'id' : IDL.Nat,
  'assignedAt' : IDL.Int,
  'assignedBy' : IDL.Text,
  'assignedTo' : IDL.Text,
  'assetId' : IDL.Nat,
  'returnedAt' : IDL.Opt(IDL.Int),
});
export const InternalRole = IDL.Variant({
  'systemAdmin' : IDL.Null,
  'airportManager' : IDL.Null,
  'procurementOfficer' : IDL.Null,
  'financeManager' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : InternalRole,
});
export const Data__2 = IDL.Record({
  'id' : IDL.Nat,
  'assetId' : IDL.Nat,
  'inspectorName' : IDL.Text,
  'inspectedAt' : IDL.Int,
  'notes' : IDL.Text,
  'outcome' : Outcome,
});
export const Data__1 = IDL.Record({
  'id' : IDL.Nat,
  'assetId' : IDL.Nat,
  'cost' : IDL.Float64,
  'nextDueDateText' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'maintenanceType' : IDL.Text,
  'performedAt' : IDL.Int,
  'performedBy' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addInspectionLog' : IDL.Func(
      [AssetId, IDL.Text, Outcome, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'addMaintenanceLog' : IDL.Func(
      [AssetId, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Float64],
      [IDL.Bool],
      [],
    ),
  'assignAsset' : IDL.Func([AssetId, IDL.Text, IDL.Text], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAsset' : IDL.Func([Specification], [AssetId], []),
  'deleteAsset' : IDL.Func([AssetId], [IDL.Bool], []),
  'getAsset' : IDL.Func([AssetId], [IDL.Opt(Data)], ['query']),
  'getAssetStats' : IDL.Func([], [Data__4], ['query']),
  'getAssignmentHistory' : IDL.Func([AssetId], [IDL.Vec(Data__3)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInspectionLogs' : IDL.Func([AssetId], [IDL.Vec(Data__2)], ['query']),
  'getMaintenanceLogs' : IDL.Func([AssetId], [IDL.Vec(Data__1)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAssets' : IDL.Func(
      [IDL.Opt(Status), IDL.Opt(Category)],
      [IDL.Vec(Data)],
      ['query'],
    ),
  'manageUserRoles' : IDL.Func([IDL.Principal, InternalRole], [IDL.Bool], []),
  'returnAsset' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAsset' : IDL.Func([AssetId, Specification], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AssetId = IDL.Nat;
  const Outcome = IDL.Variant({ 'fail' : IDL.Null, 'pass' : IDL.Null });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Status = IDL.Variant({
    'active' : IDL.Null,
    'inStorage' : IDL.Null,
    'underMaintenance' : IDL.Null,
    'retired' : IDL.Null,
  });
  const Time = IDL.Int;
  const Category = IDL.Variant({
    'vehicles' : IDL.Null,
    'other' : IDL.Null,
    'furniture' : IDL.Null,
    'itEquipment' : IDL.Null,
    'machinery' : IDL.Null,
    'officeSupplies' : IDL.Null,
  });
  const Specification = IDL.Record({
    'status' : Status,
    'assignedTo' : IDL.Opt(IDL.Text),
    'purchaseDate' : Time,
    'supplier' : IDL.Text,
    'cost' : IDL.Float64,
    'name' : IDL.Text,
    'serialNumber' : IDL.Text,
    'notes' : IDL.Text,
    'category' : Category,
    'location' : IDL.Text,
  });
  const Data = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'assignedTo' : IDL.Opt(IDL.Text),
    'purchaseDate' : Time,
    'supplier' : IDL.Text,
    'cost' : IDL.Float64,
    'name' : IDL.Text,
    'serialNumber' : IDL.Text,
    'notes' : IDL.Text,
    'category' : Category,
    'location' : IDL.Text,
  });
  const Data__4 = IDL.Record({
    'assigned' : IDL.Nat,
    'total' : IDL.Nat,
    'underMaintenance' : IDL.Nat,
    'recentlyAdded' : IDL.Nat,
  });
  const Data__3 = IDL.Record({
    'id' : IDL.Nat,
    'assignedAt' : IDL.Int,
    'assignedBy' : IDL.Text,
    'assignedTo' : IDL.Text,
    'assetId' : IDL.Nat,
    'returnedAt' : IDL.Opt(IDL.Int),
  });
  const InternalRole = IDL.Variant({
    'systemAdmin' : IDL.Null,
    'airportManager' : IDL.Null,
    'procurementOfficer' : IDL.Null,
    'financeManager' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : InternalRole });
  const Data__2 = IDL.Record({
    'id' : IDL.Nat,
    'assetId' : IDL.Nat,
    'inspectorName' : IDL.Text,
    'inspectedAt' : IDL.Int,
    'notes' : IDL.Text,
    'outcome' : Outcome,
  });
  const Data__1 = IDL.Record({
    'id' : IDL.Nat,
    'assetId' : IDL.Nat,
    'cost' : IDL.Float64,
    'nextDueDateText' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'maintenanceType' : IDL.Text,
    'performedAt' : IDL.Int,
    'performedBy' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addInspectionLog' : IDL.Func(
        [AssetId, IDL.Text, Outcome, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'addMaintenanceLog' : IDL.Func(
        [AssetId, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Float64],
        [IDL.Bool],
        [],
      ),
    'assignAsset' : IDL.Func([AssetId, IDL.Text, IDL.Text], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAsset' : IDL.Func([Specification], [AssetId], []),
    'deleteAsset' : IDL.Func([AssetId], [IDL.Bool], []),
    'getAsset' : IDL.Func([AssetId], [IDL.Opt(Data)], ['query']),
    'getAssetStats' : IDL.Func([], [Data__4], ['query']),
    'getAssignmentHistory' : IDL.Func([AssetId], [IDL.Vec(Data__3)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInspectionLogs' : IDL.Func([AssetId], [IDL.Vec(Data__2)], ['query']),
    'getMaintenanceLogs' : IDL.Func([AssetId], [IDL.Vec(Data__1)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAssets' : IDL.Func(
        [IDL.Opt(Status), IDL.Opt(Category)],
        [IDL.Vec(Data)],
        ['query'],
      ),
    'manageUserRoles' : IDL.Func([IDL.Principal, InternalRole], [IDL.Bool], []),
    'returnAsset' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAsset' : IDL.Func([AssetId, Specification], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };