/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AssetId = bigint;
export type Category = { 'vehicles' : null } |
  { 'other' : null } |
  { 'furniture' : null } |
  { 'itEquipment' : null } |
  { 'machinery' : null } |
  { 'officeSupplies' : null };
export interface Data {
  'id' : bigint,
  'status' : Status,
  'assignedTo' : [] | [string],
  'purchaseDate' : Time,
  'supplier' : string,
  'cost' : number,
  'name' : string,
  'serialNumber' : string,
  'notes' : string,
  'category' : Category,
  'location' : string,
}
export interface Data__1 {
  'id' : bigint,
  'assetId' : bigint,
  'cost' : number,
  'nextDueDateText' : [] | [string],
  'description' : string,
  'maintenanceType' : string,
  'performedAt' : bigint,
  'performedBy' : string,
}
export interface Data__2 {
  'id' : bigint,
  'assetId' : bigint,
  'inspectorName' : string,
  'inspectedAt' : bigint,
  'notes' : string,
  'outcome' : Outcome,
}
export interface Data__3 {
  'id' : bigint,
  'assignedAt' : bigint,
  'assignedBy' : string,
  'assignedTo' : string,
  'assetId' : bigint,
  'returnedAt' : [] | [bigint],
}
export interface Data__4 {
  'assigned' : bigint,
  'total' : bigint,
  'underMaintenance' : bigint,
  'recentlyAdded' : bigint,
}
export type InternalRole = { 'systemAdmin' : null } |
  { 'airportManager' : null } |
  { 'procurementOfficer' : null } |
  { 'financeManager' : null };
export type Outcome = { 'fail' : null } |
  { 'pass' : null };
export interface Specification {
  'status' : Status,
  'assignedTo' : [] | [string],
  'purchaseDate' : Time,
  'supplier' : string,
  'cost' : number,
  'name' : string,
  'serialNumber' : string,
  'notes' : string,
  'category' : Category,
  'location' : string,
}
export type Status = { 'active' : null } |
  { 'inStorage' : null } |
  { 'underMaintenance' : null } |
  { 'retired' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : InternalRole }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addInspectionLog' : ActorMethod<[AssetId, string, Outcome, string], boolean>,
  'addMaintenanceLog' : ActorMethod<
    [AssetId, string, string, string, [] | [string], number],
    boolean
  >,
  'assignAsset' : ActorMethod<[AssetId, string, string], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAsset' : ActorMethod<[Specification], AssetId>,
  'deleteAsset' : ActorMethod<[AssetId], boolean>,
  'getAsset' : ActorMethod<[AssetId], [] | [Data]>,
  'getAssetStats' : ActorMethod<[], Data__4>,
  'getAssignmentHistory' : ActorMethod<[AssetId], Array<Data__3>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInspectionLogs' : ActorMethod<[AssetId], Array<Data__2>>,
  'getMaintenanceLogs' : ActorMethod<[AssetId], Array<Data__1>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAssets' : ActorMethod<[[] | [Status], [] | [Category]], Array<Data>>,
  'manageUserRoles' : ActorMethod<[Principal, InternalRole], boolean>,
  'returnAsset' : ActorMethod<[bigint], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAsset' : ActorMethod<[AssetId, Specification], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];