/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    name: string;
    role: InternalRole;
}
export type Time = bigint;
export interface Data {
    id: bigint;
    status: Status;
    assignedTo?: string;
    purchaseDate: Time;
    supplier: string;
    cost: number;
    name: string;
    serialNumber: string;
    notes: string;
    category: Category;
    location: string;
}
export interface Data__2 {
    id: bigint;
    assetId: bigint;
    inspectorName: string;
    inspectedAt: bigint;
    notes: string;
    outcome: Outcome;
}
export interface Data__1 {
    id: bigint;
    assetId: bigint;
    cost: number;
    nextDueDateText?: string;
    description: string;
    maintenanceType: string;
    performedAt: bigint;
    performedBy: string;
}
export interface Data__3 {
    id: bigint;
    assignedAt: bigint;
    assignedBy: string;
    assignedTo: string;
    assetId: bigint;
    returnedAt?: bigint;
}
export interface Data__4 {
    assigned: bigint;
    total: bigint;
    underMaintenance: bigint;
    recentlyAdded: bigint;
}
export interface Specification {
    status: Status;
    assignedTo?: string;
    purchaseDate: Time;
    supplier: string;
    cost: number;
    name: string;
    serialNumber: string;
    notes: string;
    category: Category;
    location: string;
}
export type AssetId = bigint;
export enum Category {
    vehicles = "vehicles",
    other = "other",
    furniture = "furniture",
    itEquipment = "itEquipment",
    machinery = "machinery",
    officeSupplies = "officeSupplies"
}
export enum InternalRole {
    systemAdmin = "systemAdmin",
    airportManager = "airportManager",
    procurementOfficer = "procurementOfficer",
    financeManager = "financeManager"
}
export enum Outcome {
    fail = "fail",
    pass = "pass"
}
export enum Status {
    active = "active",
    inStorage = "inStorage",
    underMaintenance = "underMaintenance",
    retired = "retired"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addInspectionLog(assetId: AssetId, inspectorName: string, outcome: Outcome, notes: string): Promise<boolean>;
    addMaintenanceLog(assetId: AssetId, maintenanceType: string, description: string, performedBy: string, nextDueDateText: string | null, cost: number): Promise<boolean>;
    assignAsset(assetId: AssetId, assignedTo: string, assignedBy: string): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAsset(asset: Specification): Promise<AssetId>;
    deleteAsset(assetId: AssetId): Promise<boolean>;
    getAsset(assetId: AssetId): Promise<Data | null>;
    getAssetStats(): Promise<Data__4>;
    getAssignmentHistory(assetId: AssetId): Promise<Array<Data__3>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getInspectionLogs(assetId: AssetId): Promise<Array<Data__2>>;
    getMaintenanceLogs(assetId: AssetId): Promise<Array<Data__1>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listAssets(filterStatus: Status | null, filterCategory: Category | null): Promise<Array<Data>>;
    manageUserRoles(userId: Principal, role: InternalRole): Promise<boolean>;
    returnAsset(assignmentId: bigint): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateAsset(assetId: AssetId, updatedAsset: Specification): Promise<boolean>;
}
import type { Category as _Category, Data as _Data, Data__1 as _Data__1, Data__2 as _Data__2, Data__3 as _Data__3, InternalRole as _InternalRole, Outcome as _Outcome, Specification as _Specification, Status as _Status, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addInspectionLog(arg0: AssetId, arg1: string, arg2: Outcome, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addInspectionLog(arg0, arg1, to_candid_Outcome_n1(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInspectionLog(arg0, arg1, to_candid_Outcome_n1(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async addMaintenanceLog(arg0: AssetId, arg1: string, arg2: string, arg3: string, arg4: string | null, arg5: number): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addMaintenanceLog(arg0, arg1, arg2, arg3, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMaintenanceLog(arg0, arg1, arg2, arg3, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async assignAsset(arg0: AssetId, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.assignAsset(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignAsset(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n4(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n4(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAsset(arg0: Specification): Promise<AssetId> {
        if (this.processError) {
            try {
                const result = await this.actor.createAsset(to_candid_Specification_n6(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAsset(to_candid_Specification_n6(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteAsset(arg0: AssetId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAsset(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAsset(arg0);
            return result;
        }
    }
    async getAsset(arg0: AssetId): Promise<Data | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAsset(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAsset(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAssetStats(): Promise<Data__4> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssetStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssetStats();
            return result;
        }
    }
    async getAssignmentHistory(arg0: AssetId): Promise<Array<Data__3>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssignmentHistory(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssignmentHistory(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInspectionLogs(arg0: AssetId): Promise<Array<Data__2>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInspectionLogs(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInspectionLogs(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMaintenanceLogs(arg0: AssetId): Promise<Array<Data__1>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMaintenanceLogs(arg0);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMaintenanceLogs(arg0);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAssets(arg0: Status | null, arg1: Category | null): Promise<Array<Data>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAssets(to_candid_opt_n39(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n40(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAssets(to_candid_opt_n39(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n40(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async manageUserRoles(arg0: Principal, arg1: InternalRole): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.manageUserRoles(arg0, to_candid_InternalRole_n42(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.manageUserRoles(arg0, to_candid_InternalRole_n42(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async returnAsset(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.returnAsset(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.returnAsset(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n44(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n44(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateAsset(arg0: AssetId, arg1: Specification): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAsset(arg0, to_candid_Specification_n6(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAsset(arg0, to_candid_Specification_n6(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Category_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Data__1_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Data__1): Data__1 {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_Data__2_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Data__2): Data__2 {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_Data__3_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Data__3): Data__3 {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Data_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Data): Data {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_InternalRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InternalRole): InternalRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Outcome_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Outcome): Outcome {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Data]): Data | null {
    return value.length === 0 ? null : from_candid_Data_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _Status;
    assignedTo: [] | [string];
    purchaseDate: _Time;
    supplier: string;
    cost: number;
    name: string;
    serialNumber: string;
    notes: string;
    category: _Category;
    location: string;
}): {
    id: bigint;
    status: Status;
    assignedTo?: string;
    purchaseDate: Time;
    supplier: string;
    cost: number;
    name: string;
    serialNumber: string;
    notes: string;
    category: Category;
    location: string;
} {
    return {
        id: value.id,
        status: from_candid_Status_n15(_uploadFile, _downloadFile, value.status),
        assignedTo: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.assignedTo)),
        purchaseDate: value.purchaseDate,
        supplier: value.supplier,
        cost: value.cost,
        name: value.name,
        serialNumber: value.serialNumber,
        notes: value.notes,
        category: from_candid_Category_n18(_uploadFile, _downloadFile, value.category),
        location: value.location
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    assignedAt: bigint;
    assignedBy: string;
    assignedTo: string;
    assetId: bigint;
    returnedAt: [] | [bigint];
}): {
    id: bigint;
    assignedAt: bigint;
    assignedBy: string;
    assignedTo: string;
    assetId: bigint;
    returnedAt?: bigint;
} {
    return {
        id: value.id,
        assignedAt: value.assignedAt,
        assignedBy: value.assignedBy,
        assignedTo: value.assignedTo,
        assetId: value.assetId,
        returnedAt: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.returnedAt))
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: _InternalRole;
}): {
    name: string;
    role: InternalRole;
} {
    return {
        name: value.name,
        role: from_candid_InternalRole_n27(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    assetId: bigint;
    inspectorName: string;
    inspectedAt: bigint;
    notes: string;
    outcome: _Outcome;
}): {
    id: bigint;
    assetId: bigint;
    inspectorName: string;
    inspectedAt: bigint;
    notes: string;
    outcome: Outcome;
} {
    return {
        id: value.id,
        assetId: value.assetId,
        inspectorName: value.inspectorName,
        inspectedAt: value.inspectedAt,
        notes: value.notes,
        outcome: from_candid_Outcome_n34(_uploadFile, _downloadFile, value.outcome)
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    assetId: bigint;
    cost: number;
    nextDueDateText: [] | [string];
    description: string;
    maintenanceType: string;
    performedAt: bigint;
    performedBy: string;
}): {
    id: bigint;
    assetId: bigint;
    cost: number;
    nextDueDateText?: string;
    description: string;
    maintenanceType: string;
    performedAt: bigint;
    performedBy: string;
} {
    return {
        id: value.id,
        assetId: value.assetId,
        cost: value.cost,
        nextDueDateText: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.nextDueDateText)),
        description: value.description,
        maintenanceType: value.maintenanceType,
        performedAt: value.performedAt,
        performedBy: value.performedBy
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inStorage: null;
} | {
    underMaintenance: null;
} | {
    retired: null;
}): Status {
    return "active" in value ? Status.active : "inStorage" in value ? Status.inStorage : "underMaintenance" in value ? Status.underMaintenance : "retired" in value ? Status.retired : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    vehicles: null;
} | {
    other: null;
} | {
    furniture: null;
} | {
    itEquipment: null;
} | {
    machinery: null;
} | {
    officeSupplies: null;
}): Category {
    return "vehicles" in value ? Category.vehicles : "other" in value ? Category.other : "furniture" in value ? Category.furniture : "itEquipment" in value ? Category.itEquipment : "machinery" in value ? Category.machinery : "officeSupplies" in value ? Category.officeSupplies : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    systemAdmin: null;
} | {
    airportManager: null;
} | {
    procurementOfficer: null;
} | {
    financeManager: null;
}): InternalRole {
    return "systemAdmin" in value ? InternalRole.systemAdmin : "airportManager" in value ? InternalRole.airportManager : "procurementOfficer" in value ? InternalRole.procurementOfficer : "financeManager" in value ? InternalRole.financeManager : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fail: null;
} | {
    pass: null;
}): Outcome {
    return "fail" in value ? Outcome.fail : "pass" in value ? Outcome.pass : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Data__3>): Array<Data__3> {
    return value.map((x)=>from_candid_Data__3_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Data__2>): Array<Data__2> {
    return value.map((x)=>from_candid_Data__2_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Data__1>): Array<Data__1> {
    return value.map((x)=>from_candid_Data__1_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Data>): Array<Data> {
    return value.map((x)=>from_candid_Data_n13(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_InternalRole_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InternalRole): _InternalRole {
    return to_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function to_candid_Outcome_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Outcome): _Outcome {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Specification_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Specification): _Specification {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n45(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status | null): [] | [_Status] {
    return value === null ? candid_none() : candid_some(to_candid_Status_n8(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category | null): [] | [_Category] {
    return value === null ? candid_none() : candid_some(to_candid_Category_n10(_uploadFile, _downloadFile, value));
}
function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: InternalRole;
}): {
    name: string;
    role: _InternalRole;
} {
    return {
        name: value.name,
        role: to_candid_InternalRole_n42(_uploadFile, _downloadFile, value.role)
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: Status;
    assignedTo?: string;
    purchaseDate: Time;
    supplier: string;
    cost: number;
    name: string;
    serialNumber: string;
    notes: string;
    category: Category;
    location: string;
}): {
    status: _Status;
    assignedTo: [] | [string];
    purchaseDate: _Time;
    supplier: string;
    cost: number;
    name: string;
    serialNumber: string;
    notes: string;
    category: _Category;
    location: string;
} {
    return {
        status: to_candid_Status_n8(_uploadFile, _downloadFile, value.status),
        assignedTo: value.assignedTo ? candid_some(value.assignedTo) : candid_none(),
        purchaseDate: value.purchaseDate,
        supplier: value.supplier,
        cost: value.cost,
        name: value.name,
        serialNumber: value.serialNumber,
        notes: value.notes,
        category: to_candid_Category_n10(_uploadFile, _downloadFile, value.category),
        location: value.location
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    vehicles: null;
} | {
    other: null;
} | {
    furniture: null;
} | {
    itEquipment: null;
} | {
    machinery: null;
} | {
    officeSupplies: null;
} {
    return value == Category.vehicles ? {
        vehicles: null
    } : value == Category.other ? {
        other: null
    } : value == Category.furniture ? {
        furniture: null
    } : value == Category.itEquipment ? {
        itEquipment: null
    } : value == Category.machinery ? {
        machinery: null
    } : value == Category.officeSupplies ? {
        officeSupplies: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Outcome): {
    fail: null;
} | {
    pass: null;
} {
    return value == Outcome.fail ? {
        fail: null
    } : value == Outcome.pass ? {
        pass: null
    } : value;
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InternalRole): {
    systemAdmin: null;
} | {
    airportManager: null;
} | {
    procurementOfficer: null;
} | {
    financeManager: null;
} {
    return value == InternalRole.systemAdmin ? {
        systemAdmin: null
    } : value == InternalRole.airportManager ? {
        airportManager: null
    } : value == InternalRole.procurementOfficer ? {
        procurementOfficer: null
    } : value == InternalRole.financeManager ? {
        financeManager: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    active: null;
} | {
    inStorage: null;
} | {
    underMaintenance: null;
} | {
    retired: null;
} {
    return value == Status.active ? {
        active: null
    } : value == Status.inStorage ? {
        inStorage: null
    } : value == Status.underMaintenance ? {
        underMaintenance: null
    } : value == Status.retired ? {
        retired: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
